### ISSUE TITLE
project_gitlab folder not pushed?

### ISSUE THREAD

**Issue by matheo** [claudyus/odoo-gitlab#1]
Hi Claudio
I wonder you got some advances on this project.

Here in our company, we're interested to implement an open source module like this to sync issues with Odoo tasks, and we'd like to know what happened with this initiative.

Thank you very much!

**Comment by claudyus** [comment]
Hi @matheo,

your interest in odoo-gitlab module is great otherwise this project was related to an potential effort on the previous company in which I was working.

As you can see this is a really initial effort to integrate the two system but today I believe that, by architectural point of view, the usage of a light middleware like Node-Red is more appropriate to join the weebhook of an app to api of the other app and vice-versa.

Best regards

**Comment by matheo** [comment]
Thank you very much Claudio!

We'll check it out :+1:
